language: node_js
script:
- npm run precommit
before_deploy:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: qgF8P1Pg41x5amKCwvhSKfciPJ5iDRHTQvtj7hjh6248dvyvnRrJCfOFIMaeglQ0ts0L8roSgWX1TeRiVEVXrGeWrvkQ5vodAQOk8C/n5aQy9bQvCbvhfNNBhzjdMxw4IleqSKYnga9f36r76uo/BUDvPWxM3whLM3DvrMXb/tkmjFqvsvSik6qWewVf726lA/aHzf/YLnZ4S6DAgxaSuE+LKl1opP/Q8oCIZ5zNEAD0jJA5LOKxuAtz8IpQjSia7AT4v5J7L4N+/aYLCWiZ3OCHnHjsxXUQtn96tFKloZ3v7kldVnRuF0+lzFlsaQki2xBzCS0r+r/Z9YzZigZL4CYNy0BZ9PB9C1mmtqyDjxg4CbE4opNDooTrdau2G9Ibp1jpuUrR91fW3u8QdeCexLL6EgZs9pA3Gt8YaQ8NklGCIMnoQjSY7YfUKvJauYXcdpUlEuMlPcGVXKCGAPj41lyINF9qzKeeMjoN5PGx1oetVk/OfBIh6uy6WAwhwkgf5Z8vYefKnibOgToQQ721PQSd2evqG4+HQEovUlAVOtC1z+BkD0osJQ2tS2I7HPZzyhJ/biEXJfQiN5lxfPACbkQaLrXO3Ie+5+1zaw6h5cduVXCnqte7QNwCb8Mfa5HoCQS/wBsizb9pGT9fM6fzYITPX6xwZQEAW0g43JuIJws=
  app: twlevelup-melb-2017-s2-unicorn
  on:
    repo: twlevelup/MelbBuild2017S2_Unicorns
